name: Update GitHub Pages

on:
  workflow_run:
    workflows: ["Generate Code Coverage"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./C:/Clients/Singular/Automation/Tools/git-diff-tool/CoverageReport
